spring.application.name=url-shortener


spring.datasource.url=jdbc:postgresql://ep-flat-violet-a5vk2adi.us-east-2.aws.neon.tech:5432/shorten_url?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
